fint:
  application-id: fint-flyt-archive-dispatch-gateway
server:
  max-http-header-size: 40KB
spring:
  profiles:
    include:
      - flyt-kafka
      - flyt-logging
      - fint-client
      - flyt-file-client
logging:
  level:
    no.fintlabs.DispatchService: DEBUG
    org.apache.kafka: DEBUG