apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rogfk-no

resources:
  - ../../../base

commonLabels:
  fintlabs.no/org-id: rogfk.no

patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-archive-gateway_rogfk_no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "rogfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "rogfk.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/rogfk-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/rogfk-no/api/intern/arkiv"
      - op: replace
        path: "/spec/env/3/value"
        value: "https://api.felleskomponent.no"
      - op: replace
        path: "/spec/env/4/value"
        value: |
          {
            "rogfk.no":["https://role-catalog.vigoiks.no/vigo/flyt/user"],
            "vigo.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"],
            "novari.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"]
          }
    target:
      kind: Application
      name: fint-flyt-archive-gateway

  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-archive-fint-client_rogfk_no"
      - op: replace
        path: "/spec/orgId"
        value: "rogfk.no"
    target:
      kind: FintClient
      name: fint-flyt-archive-fint-client
